### ISSUE TITLE
Changes required to make it work with Huzzah32 + 2.4" TFT

### ISSUE THREAD

**Issue by sukeshak** [finger563/esp32-wireless-display#1]
This example is a great one for what I need to get started with.
Can you suggest the changes required to adapt it to the following components?

 ESP32 board
[Adafruit Huzzah32](https://www.adafruit.com/product/3405)

This uses the same display controller but a 2.4" touch screen
[TFT FeatherWing - 2.4" 320x240 Touchscreen For All Feathers](https://www.adafruit.com/product/3315)

I am still trying to get a good display library with ESP-IDF working for the above
[Discussion here without much help yet](https://www.esp32.com/viewtopic.php?f=13&t=1683&start=70)

**Comment by finger563** [comment]
Hey @sukeshak sorry for not responding to this for so long - I hadn't watched the repo so wasn't informed of the issue- let me take a look through the links you provided and get back to you!

**Comment by finger563** [comment]
If it's using the same display controller (9341) on SPI and the screen is still `320x240`, then the code should work out of the box - have you had issues with it?

**Comment by finger563** [comment]
You may need to update the pinmux to properly configure the SPI / GPIO for the connections between your ESP32 and the screen.

**Comment by sukeshak** [comment]
Thank  you for the response. I am now trying to get this working on M5stack. 
This again uses the same display controller.

Can you please elaborate on this? I am a newbie in electronics :)
You may need to update the pinmux to properly configure the SPI / GPIO for the connections between your ESP32 and the screen.

**Comment by finger563** [comment]
Take a look through [the Display Component files, specifically these defines](https://github.com/finger563/esp32-wireless-display/blob/master/src/components/Display/Display.cpp#L23) - they're how the display component is configured to talk to the display (which pins are configured and which SPI is configured)

**Comment by finger563** [comment]
closing; archiving this repo in favor of the newer https://github.com/esp-cpp/wireless-debug-display
