### ISSUE TITLE
Nice work！But only display bottom 7  lines.  How to fix? 

### ISSUE THREAD

**Issue by mxwang101** [finger563/esp32-wireless-display#2]
Also, How to get big font?  like 48 x 32 ? 

Thanks!

**Comment by finger563** [comment]
Hey @mxwang101 sorry for not responding to this for so long - I hadn't watched the repo so wasn't informed of the issue - If you want a bigger font, you'll need to generate it from a font file somehow.

[font-converter.zip](https://github.com/finger563/esp32-wireless-display/files/1864154/font-converter.zip)

I've attached a zip containing `convert_font.py` that you can use with the included (for example)  `ProximaNova Extra Condensed_BM_11x32.bmp` using a command like:

```bash
python ./convert_font.py --input ./ProximaNova\ Extra\ Condensed_BM_11x32.bmp --name my_font_variable_name --pixel_width 11 --pixel_height 32 --startIndex 2 --numCharacters 10 --horizontal
```

which will take the provided font image (1 bit BMP), assume that the characters are 11x32 and create a c array from the 10 characters started at the 3rd character (and will flip the image horizontally).

The options can be found by running:
```bash
python ./convert_font.py --help
```
or by looking at the comments for those arguments in the file.

It may take some playing with the `--horizontal` and `--vertical` parameters to get an output that works for this screen and code.

**Comment by finger563** [comment]
So you'll need to create a font `bmp` at *1 bit per pixel* for your `48x32` font, use the converter, copy the generated code into the project, and then update the display component to use the new font

**Comment by finger563** [comment]
And can you explain what you mean when you say only shows the bottom 7 lines?

**Comment by finger563** [comment]
closing; archiving this repo in favor of the newer https://github.com/esp-cpp/wireless-debug-display
